server:
  port: 8080
sprint:
  application:
    baseUrl: https://apiv2.apifootball.com/
    apiKey: 9bb66184e0c8145384fd2cc0f7b914ada57b4e8fd2e4d6d586adcc27c257a978
management:
  info:
    git:
      mode: full
name: FootBallLeagueApp
